version: '3.7'

services:

  workspace:
    build:
      context: ./docker/workspace
      dockerfile: Dockerfile
      args:
        VARIANT: "7"
        USERNAME: "vscode"
        USER_UID: 1000
        USER_GID: 1000
    env_file: ../.env
    ports:
      - "80:80"
      - "443:443"
      - "3000:3000"
      - "3306:3306"
    volumes:
      - ../:/var/www
      - ./docker/workspace/config/php.ini:/etc/php/7.4/cli/conf.d/99-php.ini
    working_dir: /var/www
    command: sleep infinity

  nginx:
    build: ./docker/nginx
    env_file: ../.env
    volumes:
      - ./docker/nginx/config:/etc/nginx/conf.d/
      - ../.docker/data/nginx/log:/var/log/nginx
      - ../:/var/www
    depends_on:
      - php
    network_mode: service:workspace

  php:
    build: ./docker/php
    env_file: ../.env
    volumes:
      - ./docker/php/config/php.ini:/usr/local/etc/php/php.ini
      - ./docker/php/config/xdebug.ini:/usr/local/etc/php/conf.d/xdebug.ini
      - ../:/var/www
    working_dir: /var/www
    network_mode: service:workspace

  node:
    build: ./docker/node
    env_file: ../.env
    tty: true
    volumes:
      - ../:/var/www
    working_dir: /var/www

  mariadb:
    image: mariadb:10.5
    env_file: ../.env
    volumes:
      - mariadb:/var/lib/mysql
      - ./docker/mariadb/config/my.cnf:/etc/mysql/conf.d/my.cnf
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_USER: ${DB_USERNAME}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_DATABASE: ${DB_DATABASE}

volumes:
  mariadb:
    driver: local
  postgres:
    driver: local
  redis:
    driver: local
