version: '3.7'

services:

  workspace:
    build:
      context: ./docker/workspace
      dockerfile: Dockerfile
      args:
        VARIANT: "7"
        USERNAME: "vscode"
        USER_UID: 1000
        USER_GID: 1000
    volumes:
      - ../:/var/www
      - ./docker/workspace/config/php.ini:/etc/php/7.4/cli/conf.d/99-php.ini
    working_dir: /var/www
    command: sleep infinity
